### ISSUE TITLE
Characters showing as deactivated

### ISSUE THREAD

**Issue by Kappus** [emfmesquita/beyondhelp#1]
Love the app, however it seems to be causing all of the characters in the Campaigns screen to be showing as deactivated (when they should still be active) when this extension is running. Confirmed by removing/re-enabling the extension, and it definitely seems to be the cause. Screenshot below. If there's any more information I can provide I'd be happy to help. Screenshot attached.

![dndbeyond](https://user-images.githubusercontent.com/27307327/34123034-e30062e4-e3f3-11e7-8df6-276a9a1e614b.png)

**Comment by emfmesquita** [comment]
I will take a look. Until I fix it (probably later today) you can disable this feature only by:
- Right click on the extension icon on chrome bar;
- Click on "Options";
- Uncheck the checkbox "Enable folders and sort on campaign pages." on the new modal.

After reloading the page it should show the default campaign page.
Thanks for the bug find and report!!! =}

**Comment by emfmesquita** [comment]
Fixed on [v0.6.3](https://github.com/emfmesquita/beyondhelp/releases/tag/v0.6.3). Currently is not possible to add folders to the deactivated list. But already planned for next version.
