### ISSUE TITLE
Calculate XP

### ISSUE THREAD

**Issue by SabreRunner** [emfmesquita/beyondhelp#2]
Can you add a feature to calculate an encounter's XP? That'll be very helpful.
If I could also divide it to characters, that'll be awesome.

**Comment by emfmesquita** [comment]
For now [Mouse0270](https://github.com/mouse0270) is dealing with encounter builder/initiative tracker on his [extension](https://github.com/mouse0270/Beyonds-Toolbox) also on the [store](https://chrome.google.com/webstore/detail/dd-toolbox/fffggleecacldpcipbechibchfikglgh). But stay tuned we might join efforts soon. Also if it does not work as planned I will be glad to implement on Beyond Help.

**Comment by mouse0270** [comment]
This is actually sorta a feature in my extension already. It shows you the total XP for an encounter added to the initiative. It is interesting you bring this up, the version of my extension I'll be pushing out tonight fixes a bug in which the XP is not recalculated in the initiative builder if you delete a monster.

**Comment by SabreRunner** [comment]
Well, I am using Beyond Interaction for rolling and stuff like that. The latest update was quite great, fixing all the little things and adding a lot of missing things. Maybe you should look into it and join with them, too.
I also tried looking for a download for your plugin but couldn't find it.

**Comment by mouse0270** [comment]
For the mast part Beyond Interaction's rolling does not conflict with my currently released plugin. In the one, I am trying to push out but meeting issues when minifying it, they will slightly overlap. For example in my next release, the plugin will do something more similar for the monster rolling attacks such as Beyond's Interaction does. We take different approaches to do the same thing.

As for joining together, all three of us are joining to make one big extension with all of our features, the problem being it is a big task that may take some time.

As for finding my extension you can find it here:

[Current pre-release found on Github.](https://github.com/mouse0270/Beyonds-Toolbox)
[Current Release on Google Chromes Store](https://chrome.google.com/webstore/detail/dd-toolbox/fffggleecacldpcipbechibchfikglgh)
[Description and info on D&D Beyond's Site](https://www.dndbeyond.com/forums/d-d-beyond-general/general-discussion/10544-d-d-toolbox-chrome-extension)

**Comment by emfmesquita** [comment]
Well Mouse said it all XD.
