### ISSUE TITLE
Feature Request: Highlight CR on details

### ISSUE THREAD

**Issue by zeg-io** [emfmesquita/beyondhelp#20]
I hate searching for the CR text in the little NPC windows... it moves around based on how much text there is.  I'd rather a copy of it at the top right as an overlay... kinda like the below.  I just used CSS to manipulate the CR value.  A better solution would be to inject a new element with a copy of part of the data... ie, split the CR value and text (which are both in the same field) . Because I didn't have a way to inject JS in the page easily I couldn't jQuery it into existence.  I think you'll get the drift.

![](https://i.imgur.com/8SANneT.png)

**Comment by emfmesquita** [comment]
#21
