### ISSUE TITLE
BUG: Latest version is screwing up the copy and disable functions!

### ISSUE THREAD

**Issue by zeg-io** [emfmesquita/beyondhelp#23]
In a campaign when I attempt to disable a character with the sort on, it bows up.

Same thing happens on character list when attempting to copy.  Unchecking the settings in the addon fixes the issue.

http://www.screencast.com/t/Mer3qBKHTj

**Comment by emfmesquita** [comment]
This only happens on chrome 71. I was just testing and could not reproduce on chrome 70, updated to 71 and bang the problem showed. I will fix it, thanks for the feedback!

**Comment by emfmesquita** [comment]
This is probably related with:  [this](https://stackoverflow.com/questions/53668098/chrome-v71-anchor-tag-scope-chain-references-inner-img-tags-scope)

I've just made a workaround and I am releasing the 0.14.3 with the fix. Thanks again for reporting the bug!
