### ISSUE TITLE
INFO: XIX is me :)

### ISSUE THREAD

**Issue by zeg-io** [emfmesquita/beyondhelp#24]
I had reported the issue to DDB, then realized it was beyond help, so I reported it here and then "closed" it there :)

**Comment by emfmesquita** [comment]
Cool! Recently I added a credits tab on options page of Beyond Help, there I added you as Zeg-io. Should I add also your DDB account link? If so would you rather be known as Zeg-io  or XIX?

**Comment by zeg-io** [comment]
Oh, cool!  "GM XIX" is good for me. for the name... goes with [www.gmxix.com](https://www.gmxix.com) :)

**Comment by emfmesquita** [comment]
Nice! Next version (v1.0.0) will have it, also a link to your site!
