### ISSUE TITLE
Not working in Chrome

### ISSUE THREAD

**Issue by DHCross** [emfmesquita/beyondhelp#25]
I may be missing something dreadfully simple, but I can't seem to get this extension to work. I don't see others are having a problem. For example, the extension is supposed to allow for folders in the characters view, but it's not there. What am I doing wrong? I have a feeling I'm going to be embarrassed when you tell me lol ...

**Comment by emfmesquita** [comment]
Lets check all this steps to try to find the problem:
- The extention should be instaled from: [chrome web store](https://chrome.google.com/webstore/detail/beyond-help/aojmegjchfjmkgmihimpplblfalnpdop);
- If go to the page chrome://extensions/ on chrome, Beyond Help (currently version v0.14.3) should be there and enabled;
- When you go to the [My Characters Page](https://www.dndbeyond.com/my-content/characters) on D&D Beyond there should be a new button **Create a Folder** on the top right of the screen:

![Create Folder](http://i.imgur.com/DrHdjpZ.png)

**Comment by emfmesquita** [comment]
Did you find out the problem or still need assistance?

**Comment by DHCross** [comment]
I figured out the NPC folders, thank you so much!

**Comment by emfmesquita** [comment]
No problem!
