### ISSUE TITLE
Folder Creation button not appearing

### ISSUE THREAD

**Issue by PlotNinja** [emfmesquita/beyondhelp#29]
My friend introduced me to this extension, as I am well renowned in my D&D group for creating tons of characters, and how I wanted a way to sort them into folders. His was working quite fine, but when I installed the extension the button to create folders doesn't show up. he told me it was next to the "Create Character" button on the "My Character Page", but it isn't appearing, and uninstalling the extension or disabling and enabling the folder option in settings doesn't change it.

Has anyone got any solutions for this? I'm probably missing something in plain sight. Attached is a screenshot of my "My Characters" page, where the "Create Folder" button should be.

![Untitled](https://user-images.githubusercontent.com/51690008/59243292-52713780-8c4e-11e9-8260-bc18a5f19df2.png)

**Comment by emfmesquita** [comment]
It took me more than 1 year to answer this, but today I made a fix for character folders, it may have fixed your issue too. The version 0.17.2 will be out as soon as Google approves it. Please add another comment if it does not fix it for you.
