### ISSUE TITLE
Character Folders not Appearing

### ISSUE THREAD

**Issue by cedavis8** [emfmesquita/beyondhelp#33]
Just installed this extension pretty specifically for the ability to sort characters into folders. Unfortunately it doesn't appear at all, my characters page is exactly the same. Any ideas why that might be?

![image](https://user-images.githubusercontent.com/10605916/83294219-938d8f00-a1b2-11ea-9fd0-54fac33145fb.png)

**Comment by zeg-io** [comment]
I just validated that it is working on my machine.  Have you turned the plugin on?  Another thought: The plugin works by injecting JavaScript and Styles into the pages, so if you have any other plugins that do the same thing, it might be conflicting?

Also, check that in the configuration for the plugin you have "Enable folders on my characters page" checked.

**Comment by cedavis8** [comment]
The plugin is on, and the configuration has the character folders enabled. I guess it's possible one of my other plugins is causing the problem? Because it doesn't work on either of my two computers. None of my other plugins seem to have that capability or functionality. I have like...a cookie tracker, honey, chrome remote desktop, adblock, adobe acrobat...

**Comment by cedavis8** [comment]
Update just turned off all my other plugins and restarted the browser. Still doesn't work. Beyond Help's other functionalities (like those with monsters) work, but not the character sorting.

**Comment by cedavis8** [comment]
Update 2: The folders work for sorting characters in my campaigns, but not on the actual characters page.

**Comment by zeg-io** [comment]
What version is installed?  I have version 0.17.1

And Chrome is v83

**Comment by cedavis8** [comment]
I have the same versions installed. Chrome is up to date as version 83, and Beyond Help v 0.17.1 is installed. it's just bizarre that all the other functionality works except for character folders. I have no idea what might be causing it.

**Comment by emfmesquita** [comment]
I made a fix today for the new problem with folders. I hope it fixes this one too. If not, please add a new comment.
