### ISSUE TITLE
New Character Sheet

### ISSUE THREAD

**Issue by SkittyBitty** [emfmesquita/beyondhelp#6]
I just wanted to inform you that the character sheets have a new design, and ask if there was a plan in place for editing this extension to work with the new style.

**Comment by emfmesquita** [comment]
Hi! 

The only feature of the extension that is present on character sheet page is the one that shows the character portrait as tab favicon. This one is already updated to the new sheet layout. 

All the other features are not related with the character sheet page. Unfortunately some of those were affected by the update, but the version 0.12.0 should have fixed the problems.

Are you having any bugs related with the extension?

**Comment by SkittyBitty** [comment]
Sorry to bother you, I'm stupid and went to the page for the wrong d&d extension. I have two and I meant this for the other one. Thank you, good day

**Comment by emfmesquita** [comment]
No problem =}
