### ISSUE TITLE
Suggestion: Make folders more foldery

### ISSUE THREAD

**Issue by zeg-io** [emfmesquita/beyondhelp#7]
Not sure where this would go in the code or I'd have submitted a pull request.

This just sets the width of the folders to 33% and keeps the format of the rest usable.  It doesn't align the way I'd like with the backgrounds, but it is more usable to me.

```css
.listing-rpgbackground div.list-row {
    float: left;
    width: 33%;
}

.ddb-characters-listing-body {
    clear: both;
}

.listing-rpgbackground .homebrew-creation-actions {
    clear: both;
    padding-top: 2em;
}
```

**Comment by emfmesquita** [comment]
Made some changes in style but used the base idea.

code: #9 

Thanks for the feedback and code! It will be on next version.
